version: '3'

services:
    nginx:
        image: service_nginx
        ports:
            - 443:443

    mariadb:
        image: service_mariadb
        environment:
            - MYSQL_ROOT_PASSWORD="${DB_PW}"
            #- MYSQL_DATABASE=wordpress
        ports: 
            - 3306:3306
            #volumes:
            # - Mariadb/db-volume/:/usr/share/nginx/
    wordpress:
        image: service_wordpress
        links:
            - mariadb:mysql
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        ports:
            - 9000:9000
            - 3306:3306
        restart: on-failure
       # volumes:
        # - ./html:/var/www/html
