version: '3'

services:
    nginx:
        image: service_nginx
        restart: always
        ports:
            - 443:443

    mariadb:
        image: service_mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD="${DB_PW}"
        volumes:
            - ./Mariadb/db-volume:/usr/share/nginx/

    wordpress:
        image: service_wordpress
        restart: always
        links:
            - mariadb:mysql
        environment:
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PW}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
        restart: on-failure
        volumes:
            - ./wordpress/ws-volume:/var/www/html