version: '3'

services:
  nginx:

	wordpress:
		image: wordpress
	    links:
	     - mariadb:mysql
	    environment:
		 - WORDPRESS_DB_USER=root
	     - WORDPRESS_DB_PASSWORD="${DB_PW}"
	    ports:
	     - 9000:9000
		 - 3306:3306
	    volumes:
	     - ./html:/var/www/html

  mariadb:
	image: mariadb
	    environment:
	     - MYSQL_ROOT_PASSWORD="${DB_PW}"
	     - MYSQL_DATABASE=wordpress
	    volumes:
	     - ./database:/var/lib/mysql
