version: '3'

services:
    nginx:
        image: service_nginx
        restart: always
        ports:
            - 443:443

    mariadb:
        image: service_mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD="${DB_PW}"
        ports: 
            - 3306:3306
        volumes:
            - Mariadb/db-volume/:/usr/share/nginx/

    wordpress:
        image: service_wordpress
        restart: always
        links:
            - mariadb:mysql
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PW}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
        ports:
            - 9000:9000
            - 3306:3306
        restart: on-failure
        volumes:
         - wordpress/ws-volume:/var/www/html

        volumes:
            mariadb:
                external: "false"
            wordpress:
                external: false