version: '3'

volumes:
    wordpress:
        #driver: local
        #driver_opts:
        #    type: none
        #    o: bind
        #    device: /home/dpuente-/data/wordpress
    mariadb:
        #driver: local
        #driver_opts:
        #    type: none
        #    o: bind
        #    device: /home/dpuente-/data/mariadb
services:
    nginx:
        depends_on:
            - wordpress
        image: service_nginx
        container_name: nginx
        restart: always
        networks: 
            - default
        ports:
            - "443:443"
            - "80:80"
        volumes:
        - wordpress:/www/

    mariadb:
        image: service_mariadb
        container_name: mariadb
        networks:
            - default
        restart: always
        env_file: .env

    wordpress:
        image: service_wordpress
        container_name: wordpress
        restart: always
        networks:
            - default
        depends_on:
            - mariadb
        env_file: .env
        environment:
            WORDPRESS_DB_USER: "${DB_U}"
            WORDPRESS_DB_PASSWORD: "${DB_PW}"
            WORDPRESS_DB_NAME: "${DB_N}"
        restart: on-failure
        volumes:
            - wordpress:/www/
networks: 
    default: