version: '3'

services:
  	nginx:
		image: nginx-service
		ports:
			443:443

	wordpress:
		image: wordpress-service
	    links:
	     - mariadb:mysql
	    environment:
		 - WORDPRESS_DB_USER=root
	     - WORDPRESS_DB_PASSWORD="${DB_PW}"
	    ports:
	     - 9000:9000
		 - 3306:3306
	    volumes:
	     - ./html:/var/www/html

  mariadb:
	image: mariadb-service
	    environment:
	     - MYSQL_ROOT_PASSWORD="${DB_PW}"
	     - MYSQL_DATABASE=wordpress
	    volumes:
	     - /Mariadb/db-volume/:/usr/share/nginx/
