FROM alpine:3.13
LABEL maintainer="dpuente-"

#update packages and install nginx
RUN apk update && apk add --no-cache nginx \
&& apk add --no-cache --upgrade bash \
&& apk add openssl && mkdir -p var/run/nginx \
&& apk add openssl openssh \
&& rm -rf /var/cache/apk/*


# create user for nginx && generate nginx folder && add permissions
RUN adduser -D -g 'www' www \
&& mkdir /www && chown -R www:www /var/lib/nginx \
&& chown -R www:www /www

#copy configuration into container
#RUN	rm -rf /etc/nginx.conf
COPY ./srcs/nginx-conf ./etc/nginx/nginx-conf

#copy front page just for testing
COPY srcs/index.html /tmp/index.html

COPY srcs/start.sh ./
RUN chmod +x ./start.sh

EXPOSE 80 443
CMD ./start.sh