FROM alpine:3.13
LABEL maintainer="dpuente-"

#install php
RUN apk add php7 wget php7-fpm php7-common php7-session php7-iconv php7-json \
    php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo \
    php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext \
    php7-ldap php7-ctype php7-dom

RUN apk add mariadb-client && apk add openrc
#downloads all wordpress files

RUN wget http://wordpress.org/latest.tar.gz\
&& tar -xzvf latest.tar.gz && rm latest.tar.gz\
&& mkdir /www \
&& mv wordpress/* /www \
&& rm -f latest.tar.gz\
&& rm -rf /var/cache/apk/*

# synbolic link between www and wordpress
RUN  ln -s www/* wordpress/

RUN sed -e '/skip-networking/s/^/#/g' -i /etc/my.cnf.d/mariadb-server.cnf

#takes the php config and pasted on the container
COPY srcs/wp-config.php www/wp-config.php
#CMD tail -f /dev/null 
#CMD /usr/bin/php -S 0.0.0.0:9000 -t /www/ && tail -f /dev/null

CMD openrc && touch /run/openrc/softlevel && rc-service php-fpm7 restart && php-fpm7 --nodaemonize